# Generated by Django 5.2.7 on 2025-11-03 20:08

import ApFaceSchool.utils
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apprenants',
            fields=[
                ('Matricule', models.CharField(max_length=15, primary_key='true', serialize=False)),
                ('Login', models.CharField(max_length=25, unique='true')),
                ('Email', models.EmailField(max_length=50, unique='true')),
                ('Nom', models.CharField(max_length=15)),
                ('Prenom', models.CharField(max_length=25)),
                ('DateNaissance', models.DateField(blank='True')),
                ('Tel', models.CharField(blank='True', max_length=20)),
                ('Niveau', models.CharField(choices=[('6EME', '6EME'), ('5EME', '5EME'), ('4EME', '4EME'), ('3EME', '3EME'), ('2ND-A', '2ND-A'), ('2ND-C', '2ND-C'), ('1ER-A', '1ER-A'), ('1ER-C', '1ER-C'), ('1ER-D', '1ER-D'), ('TLE-A', 'TLE-A'), ('TLE-D', 'TLE-D'), ('TLE-C', 'TLE-C'), ('TLE-E', 'TLE-E'), ('TLE-F', 'TLE-F')], max_length=20)),
                ('CodeEts', models.CharField(max_length=10)),
                ('Type', models.CharField(max_length=20)),
                ('Pays', models.CharField(max_length=20)),
                ('Sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('Effectif', models.IntegerField(default=0, null=True)),
                ('CodeAutorisation', models.CharField(default='bMCFILm82p', max_length=6)),
                ('CodeEnregistrement', models.CharField(max_length=6)),
                ('Photo', models.FileField(blank='True', null=True, upload_to=ApFaceSchool.utils.photo)),
                ('DateDuJour', models.DateField(blank='True', null=True)),
                ('Delai', models.IntegerField(default=45)),
                ('actif', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apprenant',
                'verbose_name_plural': 'Apprenants',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='CentreFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomEtablissement', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('Logo', models.ImageField(upload_to='Ecole_form')),
                ('lien', models.URLField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('discipline', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomClasse', models.CharField(max_length=20)),
                ('CodeEts', models.CharField(max_length=30)),
                ('Effectif', models.IntegerField(default=0)),
                ('ChefClasse', models.CharField(max_length=30)),
                ('CodeAffect', models.CharField(max_length=10, unique=True)),
                ('Niveau', models.CharField(choices=[('6EME', '6EME'), ('5EME', '5EME'), ('4EME', '4EME'), ('3EME', '3EME'), ('2ND-A', '2ND-A'), ('2ND-C', '2ND-C'), ('1ER-A', '1ER-A'), ('1ER-C', '1ER-C'), ('1ER-D', '1ER-D'), ('TLE-A', 'TLE-A'), ('TLE-D', 'TLE-D'), ('TLE-C', 'TLE-C'), ('TLE-E', 'TLE-E'), ('TLE-F', 'TLE-F')], max_length=20)),
                ('Login', models.CharField(max_length=25)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('niveau', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='publicites/')),
                ('lien', models.URLField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('TypeDoc', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeActivation', models.CharField(max_length=10, unique=True)),
                ('Delais', models.IntegerField(default=365)),
                ('Etat', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('Matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.apprenants')),
            ],
        ),
        migrations.CreateModel(
            name='CoursAdomicile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='CoursAdomiciles/')),
                ('description', models.TextField()),
                ('actif', models.BooleanField(default=True)),
                ('Discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='GroupeTravails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Groupe', models.CharField(max_length=25)),
                ('Responsable', models.CharField(blank=True, max_length=30, null=True)),
                ('Contact', models.TextField(blank=True)),
                ('logo', models.FileField(upload_to=ApFaceSchool.utils.GroupeTravail)),
                ('CodeAffect', models.CharField(max_length=10, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='GroupeEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Groupe', models.CharField(max_length=25)),
                ('Responsable', models.CharField(blank=True, max_length=30, null=True)),
                ('Contact', models.TextField(blank=True)),
                ('Etablissement', models.CharField(max_length=30)),
                ('CodeAffect', models.CharField(max_length=10, unique=True)),
                ('logo', models.FileField(upload_to=ApFaceSchool.utils.GroupeEtude)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('Niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('formateur', 'Formateur'), ('apprenant', 'Apprenant')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SujetDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReunionGrpTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('meet_link', models.URLField(blank=True)),
                ('etat', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('groupetravail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.groupetravails')),
                ('formateurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunionsformateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReunionEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('meet_link', models.URLField(blank=True)),
                ('etat', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('groupeetude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.groupeetude')),
                ('apprenants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunionAppren', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('meet_link', models.URLField(blank=True)),
                ('etat', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('maclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.maclasse')),
                ('apprenants', models.ManyToManyField(related_name='reunions_apprenant', to=settings.AUTH_USER_MODEL)),
                ('formateurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions_formateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_post', models.DateTimeField(auto_now_add=True)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ApFaceSchool.sujetdiscussion')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message_GroupeTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Objet', models.CharField(max_length=100)),
                ('Message', models.TextField(blank=True)),
                ('PiecesJointe', models.FileField(upload_to=ApFaceSchool.utils.MessGroupeTravail)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('groupetravail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.groupetravails')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message_GroupeEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Objet', models.CharField(max_length=100)),
                ('Message', models.TextField(blank=True)),
                ('PiecesJointe', models.FileField(upload_to=ApFaceSchool.utils.MessageGroupeEtude)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('groupeetude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.groupeetude')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message_Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Objet', models.CharField(max_length=100)),
                ('Message', models.TextField(blank=True)),
                ('PiecesJointe', models.FileField(blank=True, upload_to=ApFaceSchool.utils.MessageClasse)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('maclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.maclasse')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MesDossiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=50)),
                ('Etat', models.CharField(choices=[('PRIVE', 'PRIVE'), ('PUBLIC', 'PUBLIC')], max_length=10)),
                ('Observation', models.TextField(blank=True)),
                ('Document', models.FileField(upload_to=ApFaceSchool.utils.dossier_form)),
                ('Dossier_link', models.URLField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.discipline')),
                ('Niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.niveau')),
                ('TypeDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.typedocument')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MesDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Niveau', models.CharField(choices=[('6EME', '6EME'), ('5EME', '5EME'), ('4EME', '4EME'), ('3EME', '3EME'), ('2ND-A', '2ND-A'), ('2ND-C', '2ND-C'), ('1ER-A', '1ER-A'), ('1ER-C', '1ER-C'), ('1ER-D', '1ER-D'), ('TLE-A', 'TLE-A'), ('TLE-D', 'TLE-D'), ('TLE-C', 'TLE-C'), ('TLE-E', 'TLE-E'), ('TLE-F', 'TLE-F')], max_length=20)),
                ('Titre', models.CharField(max_length=50)),
                ('TypeDoc', models.CharField(choices=[('Cours', 'Cours'), ('Devoirs', 'Devoirs'), ('Exercices', 'Exercices'), ('Epreuve', 'Epreuve'), ('Exposé', 'Exposé')], max_length=20)),
                ('Etat', models.CharField(choices=[('PRIVE', 'PRIVE'), ('PUBLIC', 'PUBLIC')], max_length=10)),
                ('Observation', models.TextField(blank=True)),
                ('Document', models.FileField(upload_to=ApFaceSchool.utils.documents_Classe)),
                ('Dossier_link', models.URLField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('Discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApFaceSchool.discipline')),
                ('maclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.maclasse')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='maclasse',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupetravails',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupeetude',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Formateurs',
            fields=[
                ('Matricule', models.CharField(max_length=15, primary_key='true', serialize=False)),
                ('Login', models.CharField(max_length=25, unique='true')),
                ('Nom', models.CharField(max_length=15)),
                ('Prenom', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=50, unique='true')),
                ('DateNaissance', models.DateField(blank='True')),
                ('Tel', models.CharField(blank='True', max_length=20)),
                ('Type', models.CharField(max_length=20)),
                ('Pays', models.CharField(max_length=20)),
                ('Sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('Effectif', models.IntegerField(default=0, null=True)),
                ('CodeAutorisation', models.CharField(default='Ayd3lJxzlm', max_length=6)),
                ('CodeEnregistrement', models.CharField(max_length=6)),
                ('Photo', models.FileField(blank='True', null=True, upload_to=ApFaceSchool.utils.photo)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('Discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ApFaceSchool.discipline')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='DossiersGRPTrav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=50)),
                ('Etat', models.CharField(choices=[('PRIVE', 'PRIVE'), ('PUBLIC', 'PUBLIC')], max_length=10)),
                ('Observation', models.TextField(blank=True)),
                ('Document', models.FileField(upload_to=ApFaceSchool.utils.DocGroupeTravail)),
                ('Dossier_link', models.URLField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.discipline')),
                ('groupetravail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.groupetravails')),
                ('Niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.niveau')),
                ('TypeDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.typedocument')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DossiersGRPEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=50)),
                ('Etat', models.CharField(choices=[('PRIVE', 'PRIVE'), ('PUBLIC', 'PUBLIC')], max_length=10)),
                ('Observation', models.TextField(blank=True)),
                ('Document', models.FileField(upload_to=ApFaceSchool.utils.DocGroupeEtude)),
                ('Dossier_link', models.URLField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.discipline')),
                ('groupetude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.groupeetude')),
                ('Niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.niveau')),
                ('TypeDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.typedocument')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='apprenants',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appren_GroupeEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('Matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.apprenants')),
                ('groupetude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.groupeetude')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('Matricule', 'groupetude'), name='groupeetudeapprenant')],
            },
        ),
        migrations.CreateModel(
            name='form_grpe_travails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('Matricule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.formateurs')),
                ('groupetravail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.groupetravails')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('Matricule', 'groupetravail'), name='groupetravailFormateur')],
            },
        ),
        migrations.CreateModel(
            name='apprenant_maclasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.apprenants')),
                ('maclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.maclasse')),
            ],
            options={
                'unique_together': {('maclasse', 'apprenant')},
            },
        ),
        migrations.CreateModel(
            name='SoluExoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Solution', models.FileField(upload_to=ApFaceSchool.utils.Solution_doc)),
                ('Contenu', models.TextField(blank=True)),
                ('Etat', models.CharField(choices=[('PRIVE', 'PRIVE'), ('PUBLIC', 'PUBLIC')], max_length=10)),
                ('Note', models.CharField(blank=True, default='', max_length=5)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.discipline')),
                ('Niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.niveau')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.mesdocuments')),
                ('maclasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApFaceSchool.maclasse')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('username', 'documents'), name='SolutionDocuments')],
            },
        ),
        migrations.CreateModel(
            name='PartenariatGroupTrav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('GroupeTravDemandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandeurs', to='ApFaceSchool.groupetravails')),
                ('GroupeTravPartenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partenaires', to='ApFaceSchool.groupetravails')),
                ('ProfsDemandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandeursProfs', to=settings.AUTH_USER_MODEL)),
                ('ProfsPartenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partenairesprofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('GroupeTravDemandeur', 'GroupeTravPartenaire'), name='GroupeTravPartenaire')],
            },
        ),
        migrations.CreateModel(
            name='PartenariatGroupEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('GroupeEtudDemandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandeurs', to='ApFaceSchool.groupeetude')),
                ('GroupeEtudPartenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partenaires', to='ApFaceSchool.groupeetude')),
                ('ApprenDemandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandeursAppre', to=settings.AUTH_USER_MODEL)),
                ('ApprenPartenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partenairesAppre', to=settings.AUTH_USER_MODEL)),
                ('Auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('GroupeEtudDemandeur', 'GroupeEtudPartenaire'), name='GroupeEtudePartenaire')],
            },
        ),
        migrations.CreateModel(
            name='PartenariatClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('ClassDemandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandeurs', to='ApFaceSchool.maclasse')),
                ('ClassPartenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partenaires', to='ApFaceSchool.maclasse')),
                ('ProfDemandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandeursProf', to=settings.AUTH_USER_MODEL)),
                ('ProfPartenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partenairesprof', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ClassDemandeur', 'ClassPartenaire'), name='ClassePartenaire')],
            },
        ),
    ]
