# Generated by Django 5.2.7 on 2025-11-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApFaceSchool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenants',
            name='CodeAutorisation',
            field=models.CharField(default='W0SQzJOxEX', max_length=6),
        ),
        migrations.AlterField(
            model_name='formateurs',
            name='CodeAutorisation',
            field=models.CharField(default='qFdapovwan', max_length=6),
        ),
    ]
