# Generated by Django 5.2.7 on 2025-11-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApFaceSchool', '0002_alter_apprenants_codeautorisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenants',
            name='CodeAutorisation',
            field=models.CharField(default='De0DKlbssU', max_length=6),
        ),
        migrations.AlterField(
            model_name='formateurs',
            name='CodeAutorisation',
            field=models.CharField(default='SidkKMVpSP', max_length=6),
        ),
    ]
