# Generated by Django 5.2.7 on 2025-11-13 19:27

import ApFaceSchool.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApFaceSchool', '0005_alter_apprenants_codeautorisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenants',
            name='CodeAutorisation',
            field=models.CharField(default='98571223', max_length=8, unique='true'),
        ),
        migrations.AlterField(
            model_name='apprenants',
            name='Photo',
            field=models.FileField(blank='True', default='/static/images/default_avatar.png', null=True, upload_to=ApFaceSchool.utils.photo),
        ),
        migrations.AlterField(
            model_name='formateurs',
            name='CodeAutorisation',
            field=models.CharField(default='41908288', max_length=8, unique='true'),
        ),
    ]
