# Generated by Django 5.2.7 on 2025-11-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApFaceSchool', '0006_alter_apprenants_codeautorisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenants',
            name='QuotaDossier',
            field=models.IntegerField(blank='True', default=1000000),
        ),
        migrations.AddField(
            model_name='formateurs',
            name='QuotaDossier',
            field=models.IntegerField(blank='True', default=1000000),
        ),
        migrations.AlterField(
            model_name='apprenants',
            name='CodeAutorisation',
            field=models.CharField(default='67080901', max_length=8, unique='true'),
        ),
        migrations.AlterField(
            model_name='formateurs',
            name='CodeAutorisation',
            field=models.CharField(default='91637346', max_length=8, unique='true'),
        ),
    ]
