# Generated by Django 5.2.7 on 2025-11-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApFaceSchool', '0007_apprenants_quotadossier_formateurs_quotadossier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursadomicile',
            name='taille',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dossiersgrpetude',
            name='taille',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dossiersgrptrav',
            name='taille',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mesdocuments',
            name='taille',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mesdossiers',
            name='taille',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soluexoclasses',
            name='taille',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apprenants',
            name='CodeAutorisation',
            field=models.CharField(default='95621668', max_length=8, unique='true'),
        ),
        migrations.AlterField(
            model_name='apprenants',
            name='QuotaDossier',
            field=models.BigIntegerField(blank='True', default=1000000),
        ),
        migrations.AlterField(
            model_name='formateurs',
            name='CodeAutorisation',
            field=models.CharField(default='05311872', max_length=8, unique='true'),
        ),
        migrations.AlterField(
            model_name='formateurs',
            name='QuotaDossier',
            field=models.BigIntegerField(blank='True', default=1000000),
        ),
    ]
