# Generated by Django 5.2.7 on 2025-11-18 13:35

import ApFaceSchool.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApFaceSchool', '0008_coursadomicile_taille_dossiersgrpetude_taille_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenants',
            name='CodeAutorisation',
            field=models.CharField(default='55331915', max_length=8, unique='true'),
        ),
        migrations.AlterField(
            model_name='formateurs',
            name='CodeAutorisation',
            field=models.CharField(default='76679816', max_length=8, unique='true'),
        ),
        migrations.AlterField(
            model_name='mesdossiers',
            name='taille',
            field=models.BigIntegerField(default=ApFaceSchool.utils.taillefichier),
        ),
    ]
