# Generated by Django 5.2.7 on 2025-11-19 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApFaceSchool', '0009_alter_apprenants_codeautorisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenants',
            name='CodeAutorisation',
            field=models.CharField(default='62843683', max_length=8, unique='true'),
        ),
        migrations.AlterField(
            model_name='apprenants',
            name='QuotaDossier',
            field=models.BigIntegerField(blank='True', default=1048576),
        ),
        migrations.AlterField(
            model_name='formateurs',
            name='CodeAutorisation',
            field=models.CharField(default='96877684', max_length=8, unique='true'),
        ),
        migrations.AlterField(
            model_name='formateurs',
            name='QuotaDossier',
            field=models.BigIntegerField(blank='True', default=1048576),
        ),
        migrations.AlterField(
            model_name='mesdossiers',
            name='taille',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuotaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_gb', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='new', max_length=32)),
                ('payment_status', models.CharField(default='none', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
