# Generated by Django 5.2.7 on 2025-11-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApFaceSchool', '0010_alter_apprenants_codeautorisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeetude',
            name='QuotaDossier',
            field=models.BigIntegerField(blank='True', default=1048576),
        ),
        migrations.AddField(
            model_name='groupetravails',
            name='QuotaDossier',
            field=models.BigIntegerField(blank='True', default=1048576),
        ),
        migrations.AddField(
            model_name='maclasse',
            name='QuotaDossier',
            field=models.BigIntegerField(blank='True', default=1048576),
        ),
        migrations.AlterField(
            model_name='apprenants',
            name='CodeAutorisation',
            field=models.CharField(default='59564548', max_length=8, unique='true'),
        ),
        migrations.AlterField(
            model_name='formateurs',
            name='CodeAutorisation',
            field=models.CharField(default='14418914', max_length=8, unique='true'),
        ),
    ]
